type move =
  | UP_CLOCKWISE
  | UP_COUNTER_CLOCKWISE
  | UP_TWICE
  | DOWN_CLOCKWISE
  | DOWN_COUNTER_CLOCKWISE
  | DOWN_TWICE
  | RIGHT_CLOCKWISE
  | RIGHT_COUNTER_CLOCKWISE
  | RIGHT_TWICE
  | LEFT_CLOCKWISE
  | LEFT_COUNTER_CLOCKWISE
  | LEFT_TWICE
  | FRONT_CLOCKWISE
  | FRONT_COUNTER_CLOCKWISE
  | FRONT_TWICE
  | BACK_CLOCKWISE
  | BACK_COUNTER_CLOCKWISE
  | BACK_TWICE
  | ROTATE_Y_CLOCKWISE
  | ROTATE_Y_COUNTER_CLOCKWISE
  | ROTATE_Y_TWICE
  | ROTATE_X_CLOCKWISE
  | ROTATE_X_COUNTER_CLOCKWISE
  | ROTATE_X_TWICE
  | ROTATE_Z_CLOCKWISE
  | ROTATE_Z_COUNTER_CLOCKWISE
  | ROTATE_Z_TWICE
  | FRONT_WIDE_CLOCKWISE
  | FRONT_WIDE_COUNTER_CLOCKWISE

val make : Cube.cube -> move -> Cube.cube
val to_notation : move -> string
val from_notation : string -> (move, string) result
val execute_scramble : string -> Cube.cube
val moves_to_string : move list -> string
